on:
  push:
    branches:
      - main    
  pull_request:

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]        
    steps:
    - uses: actions/checkout@v1      
    - name: Run Continuous Integration
      shell: pwsh
      run : |
        cd ./__tests__
        # Invoke-Pester -Output Detailed